pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Parchment'
            url = 'https://maven.parchmentmc.org'
        }
	}
}

rootProject.name = 'SnekCraft'

gradle.ext.modid = 'snekcraft'
gradle.ext.modversion = '1.2.1'
gradle.ext.modname = 'Snekcraft'
gradle.ext.moddesc = 'A mod that adds snakes.'
gradle.ext.modauthor = 'Raspix, Piedpipecleaner, '
gradle.ext.modlicense = 'All Rights Reserved'
gradle.ext.modgroup = 'com.raspix.snekcraft'

gradle.ext.forgegroup = gradle.ext.modgroup
gradle.ext.forgename = rootProject.name + '-Forge'

gradle.ext.fabricgroup = gradle.ext.modgroup
gradle.ext.fabricname = rootProject.name + '-Fabric'

include 'forge'
include 'fabric'